# Generated by Django 3.1.7 on 2021-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='boost_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maincycle',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
