# Generated by Django 3.1.7 on 2021-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210520_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='auto_click_power',
            field=models.IntegerField(default=0),
        ),
    ]
